### ISSUE TITLE
Visual Editor: First character in title / description ends up at the end of the line

### ISSUE THREAD

**Issue by tisto** [plone/volto#187]
1) Checkout visual-editor branch
2) Run frontend and backend
3) Create RichPage type with "arrangement" and "tiles" Text fields
4) Log into the frontend as admin
5) Go to add "RichPage" form
6) Click into the "title" field once
-> nothing happens, I have to click twice to get to the editable title field
7) Type title "1234"
-> After typing in the first character into the title field the cursor switched to the position before the "1" and not after as it should. This leads to "2341" in the title field instead of "1234".
![add richpage](https://user-images.githubusercontent.com/632105/41818140-bc58e208-77a8-11e8-81ee-682c2729e7c6.png)

Same happend in the description field. After that I can not add anything to the other tiles fields.

I see lots of warnings and two errors in the js console:

1) 
Uncaught TypeError: Cannot read property 'getIn' of undefined getUpdatedSelectionState.js:33 
2) Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.

**Comment by robgietema** [comment]
Fixed by #195

**Comment by tisto** [comment]
@robgietema the problem still persists. Go to https://plone-react.kitconcept.io/ and add a new document, then tab into the description and start typing. 

Though, I could narrow it down to when I create a new document. It works well on existing docs.
