### ISSUE TITLE
Weird interaction with yarn tests

### ISSUE THREAD

**Issue by tiberiuichim** [plone/volto#2111]
**Describe the bug**

Cannot run tests when making a change in Volto source code. I get:

```
Determining test suites to run...

  ● Test suite failed to run

    Configuration error:

    Could not locate module @plone/volto/babel mapped as:
    /home/tibi/work/volto/src/babel.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/@plone\/volto\/(.*)$/": "/home/tibi/work/volto/src/$1"
      },
      "resolver": null
    }

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:501:17)
          at Array.reduce (<anonymous>)
      at SearchSource.findRelatedTests (node_modules/@jest/core/build/SearchSource.js:280:30)
      at SearchSource.findTestRelatedToChangedFiles (node_modules/@jest/core/build/SearchSource.js:363:14)


Done in 4.36s.
```

**To Reproduce**

With a Volto git clone, make a change in source code (I've inserted a simple comment in src/config/index.js). Then run tests with `yarn test`, select to run "all" if prompted.

**Expected behavior**

Tests are run

**Additional context**

I was able to fix this problem by adding: 
```
"@plone/volto/babel": "<rootDir>/babel.js",
```
to `moduleNameMapper` in jest key of package.json.

**Comment by tiberiuichim** [comment]
Fixed by https://github.com/plone/volto/commit/9a72a46b6ec576e11bdecfc4b1f4d4a7b16d3896

**Comment by ksuess** [comment]
I still have this problem with Volto master from today 02.06.2021
@tiberiuichim 's suggestion to add "@plone/volto/babel": "<rootDir>/babel.js", to moduleNameMapper helps.
