### ISSUE TITLE
Docs: Remove buildout from install backend

### ISSUE THREAD

**Issue by stevepiercy** [plone/volto#4195]
In [Install a Plone backend locally without Docker](https://6.docs.plone.org/volto/configuration/backend.html#install-a-plone-backend-locally-without-docker) the Volto docs still recommend to use buildout. The new method is now in https://6.docs.plone.org/install/install-from-packages.html.

I would suggest that we remove buildout references and instead direct users to the new way.

@tiberiuichim @sneridagh opinions?

**Comment by tiberiuichim** [comment]
Of course

**Comment by stevepiercy** [comment]
On second thought, I think the entire page should be removed, and the Configuration section should have a new introduction to direct developers to install Plone via containers or packages using the new methods.

But this ties back into several open issues about reorganizing the Volto install docs within the Plone 6 docs. https://github.com/plone/volto/issues/3998#issuecomment-1328914246

Because there are so many different parts to install Volto, I created a new mini-project, [Install Docs](https://github.com/orgs/plone/projects/16/views/1).

Once we take inventory of all the open issues related to Install Docs, then we can come up with a plan for how to reorganize things.

**Comment by SaiRev0** [comment]
Is the issue still open, I would like to work on this issue

**Comment by stevepiercy** [comment]
@SaiRev0 no. See comment in https://github.com/plone/volto/pull/4212#issuecomment-1369706496.

If you want an easy issue to work on, please search for the label ["41 lvl: easy"](https://github.com/plone/volto/labels/41%20lvl%3A%20easy). Thank you!

**Comment by SaiRev0** [comment]
@stevepiercy Thanks for the info

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/volto/pull/5287

**Comment by stevepiercy** [comment]
@davisagli partially fixed, I think, unless I misunderstand. We need to remove the section, correct?

**Comment by davisagli** [comment]
@stevepiercy The info I left on the page is still relevant.

**Comment by stevepiercy** [comment]
@davisagli I mean, if you say it is fixed, then it should be closed, right? What else needs to be done for this issue?

**Comment by davisagli** [comment]
I think it is done, I just missed closing it.

**Comment by stevepiercy** [comment]
Ah, yeah, and needing to update submodule tips, plus cache, it took a while to get removed. We're good!
